### ISSUE TITLE
Notifications do not disappear when checkin to local server

### ISSUE THREAD

**Issue by shiena** [SRombauts/UEPlasticPlugin#105]
Environment:
- OS: Windows10
- Unreal Engine: 5.0.2
- Plugin: 071fa325487f311e684417f1809d024a0c44ab36

Steps to reproduce
1. Set `local` to Server URL
2. press the create button
3. press the accept button
![image](https://user-images.githubusercontent.com/1295639/174505928-3cac7bbe-9457-45f0-9eef-e29278eeec23.png)

Actual behaviour
Checking file notification does not disappear
![image](https://user-images.githubusercontent.com/1295639/174505994-03ece2ca-8a25-4d9d-9bff-7ce77b138979.png)

**Comment by shiena** [comment]
I'm sorry. After waiting for a while, the notification disappeared.

**Comment by SRombauts** [comment]
Hello, thanks for reporting! This is actually a knonw issue; when creating the workspace, if you Accept Settings before the notification disapears, it can stay forever.

So I will reopen this in order to properly fix it (low priority, but still)

Cheers !

**Comment by SRombauts** [comment]
This has been fixed as part of https://github.com/PlasticSCM/UEPlasticPlugin/pull/94 Fix ongoing workspace creation shouldn't be interrupted if the users close the window too early, released as part of https://github.com/SRombauts/UEPlasticPlugin/releases/tag/1.9.0 🎉
