### ISSUE TITLE
ERROR: System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by lehuan5062** [SRombauts/UEPlasticPlugin#109]
Hello, if I install this version of plugin, the plugin will be duplicated, the error "System.ArgumentException: An item with the same key has already been added" will occur. I need to delete and use the old one which shipped with UE5.
Do you know how to delete the shipped one? I can't either find it in the plugin folder or don't know the folder name.

**Comment by lehuan5062** [comment]
"C:\Program Files\Epic Games\UE_5.0\Engine\Plugins\Developer\PlasticSourceControl"

**Comment by SRombauts** [comment]
Can you please let me know on what platform this error occurs? Windows, but which compiler? Or on what case ; how are you building?

I am asking because I never had the issue, though I know some people told me it happened to them

**Comment by lehuan5062** [comment]
Hello!
This happened when I package the project with UE5's Project Launcher.
I use Windows 10 and Visual Studio 2019.
There was another Plastic SCM plugin inside `C:\Program Files\Epic Games\UE_5.0\Engine\Plugins\Developer\PlasticSourceControl`. Deleting it should fix the problem.
