### ISSUE TITLE
Update last revision of all assets

### ISSUE THREAD

**Issue by Acren** [SRombauts/UEPlasticPlugin#112]
Hey there,

Maybe a bit of an unusual request but I'm currently working on some editor tools and need a way to access the last revision date of essentially every asset in the project, for data validation purposes.

I believe to do this I'd need to run an update status command first, however I can't find a way to do this that works in the current implementation.

Calling an FUpdateStatus command with SetUpdateHistory, SetCheckingAllFiles, SetGetOpenedOnly all to true appears to update all of the assets, but it doesn't seem to provide any history on the states so I'm unable to access the last modified date using this method.

Calling one with every file explicitly set appears to take much longer and eventually timeout.

Would you have any recommendations on how to achieve this?

Much thanks!

Edit: Suppose I should be clear I just need the head revision of the assets and not the entire history!

**Comment by SRombautsU** [comment]
Hello Acren,
I do think that you need to call with the explicit list of all files, with SetUpdateHistory
And yes it does take a lot longer because it does add a lot more work for both the plugin and Plastic SCM.
Are you using one of the recent version from this repository, as opposed to using the obsolete plugin coming with the Unreal Editor?

**Comment by Acren** [comment]
Hey, sorry for the delay. We're using 1.6.2 from this repo.

In the end I decided to run "cm find revisions" directly in Plastic to gather the revision dates as it's much faster than processing Update Status with every asset in the project and so it doesn't timeout.

Thanks anyway!
