### ISSUE TITLE
Global Source Control Refresh only check local status

### ISSUE THREAD

**Issue by SRombautsU** [SRombauts/UEPlasticPlugin#115]
"Refresh" calls in "cm status" for all the assets in the repository, but not all the additional commands it would nee to retrieve extra info like the locks and the detection of changes

 1. If I checkout or revert some assets from the Plastic SCM GUI, using the Source Control -> "Refresh" in Unreal will correctly update the local "status" of the files (it uses "cm status" for that)
 2. But
    1. if someone else checkout & lock some assets on another workspace, using this "Refresh" won't check all the locks on the server, as an optimization to avoid too much network calls
        1. this could in fact be improved using a separate "cm lock list" command, so I'll fill a task for that
    2. if someone else submit a newer revision of an asset, using this "Refresh" won't actually check what are the latest revisions for all assets as ab optimization
        1. there is no good way to do this, it needs to be local & focused to the normal refresh of the Content Browser current view (even though we could offer an option usable on small projects)

**Comment by SRombauts** [comment]
Note that the Plastic SCM GUI uses a "merge" command to check periodically if there are any incoming changes, which is something that would make sense to use instead of expansive calls to fileinfo

**Comment by SRombauts** [comment]
I removed the refresh button from the global menu for release 1.9.0
