### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dacanizares** [SRombauts/UEPlasticPlugin#119]
In order to run the plugin on Linux follow these steps:

1. (Skip this step - already fixed https://github.com/PlasticSCM/UEPlasticPlugin/commit/935cefe197dada89d22f18a0a16c3661e05a665d) Modify PlasticSourceControlShell.h, line 13 :
   
    ```cpp
    // BEFORE
    constexpr TCHAR* pchDelim = TEXT("\n");
    
    // NOW
    constexpr const TCHAR* pchDelim = TEXT("\n");
    ```
    
2. After that change, the plugin must compile and run on Linux, but the working directory is not being handled correctly by some component, so you can create a custom bash script to set the right path for your project:

    ```bash
    #!/bin/bash
    cd /home/user/source/ue/project-location
    cm "$@"
    ```
    
The script will go to the project location and then pass all arguments to the **cm** command. When the extension asks for the PlasticSCM Path, instead of *cm*, put your bash script location. And that's it. A little bit hacky but it works while we get a propper fix.

**Comment by SRombauts** [comment]
Hey @dacanizares, thanks for the heads up!

I submitted a fix for the `constexpr const TCHAR* pchDelim = TEXT("\n");`

As for the script, I think that I read something similar some time ago about git Git plugin, and/or the Plastic plugin on MacOS...
but I never tried to dig into the issue myself yet.

Do you have some logs showing the error?

Isn't it something that we could fix in the source code, eg in `PlasticSourceControlShell.cpp` in _StartBackgroundPlasticShell() to set the proper InWorkingDirectory?

Thanks!

**Comment by dacanizares** [comment]
Hi @SRombauts!

Yesterday I saw that all variables have correct values. My suspicion it's that FPlatformProcess::CreateProc doesn't use correctly the *WorkingDirectory* on Linux (or maybe the **cm** executable itself, not sure). I will try to find out why that is happening, but at least it's working. 

The log just says that */home/user/unreal/Build/Linux/* (the location of the UnrealEditor executable) is not a PlasticCM workspace.

Thanks!

**Comment by dacanizares** [comment]
Yes, that's the issue. The variable OptionalWorkingDirectory is not being used on the Unreal code. 
![image](https://user-images.githubusercontent.com/5238966/209195518-766ee461-9eb1-4fb8-85be-ac51f8a908fd.png)

**Comment by SRombauts** [comment]
Hum, is this in Unreal Engine 5? I though I saw the variable being used...

If it's really not used, I imagine that we can workaround this by changing directory in Unreal before creating the process and changing back right after

**Comment by dacanizares** [comment]
@SRombauts here is the PR with that fix: https://github.com/SRombauts/UEPlasticPlugin/pull/120

I've tested locally and it's working.

If you have comments or any user reports further issues, please let me know.

**Comment by SRombauts** [comment]
Thank you for your awesome contribution @dacanizares

Sébastien

**Comment by dacanizares** [comment]
Thanks @SRombauts!
