### ISSUE TITLE
Diff against Depot doesn't work if the path contains a space (1.8.1)

### ISSUE THREAD

**Issue by Ewan-Selkirk** [SRombauts/UEPlasticPlugin#130]
After upgrading the plugin from 1.8.0 to 1.8.1 the 'Diff against Depot' function no longer works, stating that is is unable to find the revision twice.

![image](https://github.com/SRombauts/UEPlasticPlugin/assets/49927837/6d83b839-e965-4101-a609-cae79fa71d84)

Downgrading back to 1.8.0 fixes the issues.
This is happening with Unreal Engine 5.1 not built from source.

**Comment by SRombauts** [comment]
Thanks for reporting this, and for all the details, I'll take a quick look and will let you know!

**Comment by SRombauts** [comment]
The old command was

```
LogSourceControl: Verbose: RunDumpToFile: 'cm cat "rev:C:/Users/sebastien.rombauts/Documents/Unreal Projects/UE52TestSpacesInPath/Content/StarterContent/Blueprints/Blueprint_CeilingLight.uasset#cs:1@UE52TestSpacesInPath@SRombautsU@cloud" --raw --file="C:/Users/sebastien.rombauts/Documents/Unreal Projects/UE52TestSpacesInPath/Saved/Diff/temp-cs1-Blueprint_CeilingLight.uasset"'
```

while the new one is now

```
[2023.07.12-12.57.43:898][578]LogSourceControl: Verbose: RunCommand: 'getfile rev:C:/Users/sebastien.rombauts/Documents/Unreal Projects/UE52TestSpacesInPath/Content/StarterContent/Blueprints/Blueprint_CeilingLight.uasset#cs:1@UE52TestSpacesInPath@SRombautsU@cloud --raw --file="C:/Users/sebastien.rombauts/Documents/Unreal Pro' (334 chars, 0 files) 
```

Note that we dropped for some reason the double quotes around the "RevSpec" rev:C:/xxx

**Comment by SRombauts** [comment]
So the fix in `RunGetFile()` is simply to change back from 

```
	Parameters.Add(InRevSpec);
```

to

```
	Parameters.Add(FString::Printf(TEXT("\"%s\""), *InRevSpec));
```

**Comment by SRombauts** [comment]
Thanks again for reporting this, I fixed it.
Are you able to install the dev version from the master branch, or will you require a new bugfix release @Ewan-Selkirk?

**Comment by Ewan-Selkirk** [comment]
Thank you for the quick fix! 
I'll give installing the plugin from the master branch a go when I get the chance

**Comment by Ewan-Selkirk** [comment]
Just got it installed and everything is working.
Thanks again!
