### ISSUE TITLE
View Branches window

### ISSUE THREAD

**Issue by mjolner36** [SRombauts/UEPlasticPlugin#137]
How open View Branches window in UE 5.3?
![IMG_20240108_021146_412.jpg](https://github.com/SRombauts/UEPlasticPlugin/assets/16782151/9ca21237-2bd4-4b4a-bd31-82412d8bf49e)

**Comment by SRombauts** [comment]
Hi,

Provided that your are correctly using the plugin v1.9.0 (check the tooltip over the menu or the revision control login/settings window or the logs LogSourceControl), you should be able either to;

1. Click on the name of the current Branch now displayed on the bottom status toolbar 
2. Use the menu Revision Control -> View Branches 
3. Use the menu Tools -> View Branches

I'll check the documentation and make sure to add details as appropriate!

Let me know how it works for you,
Sébastien

**Comment by SRombauts** [comment]
Hey @mjolner36, I have added a few details to the README and updated the screenshot of the Revision Control menu showing the "View Branches" entry.

**Comment by mjolner36** [comment]
I fix my problem.

I found a problem with the fact that the plugin is defaulted to the old version
![image](https://github.com/SRombauts/UEPlasticPlugin/assets/16782151/cd086b46-443f-4933-93ab-a6caf4f8e4f1)

**Comment by SRombauts** [comment]
Good! That was indeed my initial thought, and the first thing to check.
