### ISSUE TITLE
Cannot check-out any assets in the Unreal Project while uploading a check-in through the Unity Version Control app

### ISSUE THREAD

**Issue by arraybercov** [SRombauts/UEPlasticPlugin#140]
Hi I keep the plugin updated and for the past few days I've noticed a new issue that I cannot check-out any UE assets when I'm checking-in through the UVC app. 

I'm testing by trying to check-out random assets in the project that have nothing to do with what I'm uploading. Any ideas?

**Comment by SRombauts** [comment]
Hello @arraybercov, I am sorry that I didn't see your message earlier! Did you find a solution? Was this fixed by updating the plugin (or by going back)?
I have recently released a new version 1.10.0 of the plugin https://github.com/SRombauts/UEPlasticPlugin/releases/tag/1.10.0

**Comment by SRombautsU** [comment]
Hey, do you have any details on when it first happened?
It could help if you can try to get back from a few commit and pinpoint the issue

**Comment by SRombauts** [comment]
Hello, I am closing this issue as I have nothing material to support it.
But please feel free to reopen it if you can provide logs or track the regression down to a specific commit 🙏
