### ISSUE TITLE
Getting connection error while Plastic GUI works fine on UE 5.4.4

### ISSUE THREAD

**Issue by amadjunaid** [SRombauts/UEPlasticPlugin#145]
I built the engine from source with plugin source also upldated to the latest 1.11 release. I am getting the following error:
![image](https://github.com/user-attachments/assets/5560691b-43dd-418d-b1c5-5c5c92585f09)

![image](https://github.com/user-attachments/assets/f27293f3-19e7-4f42-8f5e-6a0a633e035f)

from the log

Branch /main@testrepo@ssl://uvc.testserver.net:8088
LogSourceControl: Warning: RunCommand: 'checkconnection --server=ssl://uvc.testserver.net:8088 ' (in 0.052s) output (33 chars):
Error: Das Handle ist ung?ltig.
SourceControl: Error: Command: Connect, Error: Error: Das Handle ist ung?ltig.
LogSourceControl: Connect processed in 0.062s
SourceControl: Error: Connection Error: Error: Das Handle ist ung?ltig.

**Comment by SRombautsU** [comment]
Hello,
I don't think that this is a bug in the plugin, or even in the Unity Version Control / Plastic command line tool.
The error you had 
`Error: this handle is invalid.`
means that the --server=ssl://uvc.testserver.net:8088 cannot be resolved to a valid server

Ideally you should double check with the Desktop GUI and then with the Windows command line, by using the same command
`cm checkconnection --server=ssl://uvc.testserver.net:8088 `

If you have more issues, you should reach out directly to our support, they would be able to help much faster than I could (sorry about that).
To report an issue, please create a support ticket as it helps sort the priorities [Unity Version Control support](https://support.unity.com/hc/en-us/requests/new?ticket_form_id=360001051792).
