### ISSUE TITLE
Unreal engine 5.5.0 ? 

### ISSUE THREAD

**Issue by Renan-Yilmaz** [SRombauts/UEPlasticPlugin#147]
There is any update to support the new engine version 5.5.0 ?

**Comment by SRombauts** [comment]
Hello! Yes, Unreal Engine 5.5 support was implemented some time ago https://github.com/PlasticSCM/UEPlasticPlugin/pull/124 and was released yesterday https://github.com/SRombauts/UEPlasticPlugin/releases/tag/1.12.0 🎉 

Now, if the question is about getting the update on Fab.com https://www.fab.com/listings/42f9c431-d7a7-4e09-af55-fb4b896e9c97 it is currently being reviewed by Epic Games, which typically takes a couple of days at least.

Cheers!

**Comment by SRombauts** [comment]
Hey @Renan-Yilmaz, I am happy to report that Epic Games published our newest version 1.12.0 of the Unity Verison Control/Plastic SCM plugin in Fab.com https://www.fab.com/listings/42f9c431-d7a7-4e09-af55-fb4b896e9c97 
You can download it from the Epic Games Launcher.

Let me know how it works for you.
Cheers!
Sébastien

**Comment by Renan-Yilmaz** [comment]
Hey @SRombauts  Thank's for your feedback all good for me now ! 

Cheers 
Renan !
