### ISSUE TITLE
Crash while Sync/Update workspace in UE4

### ISSUE THREAD

**Issue by levantail** [SRombauts/UEPlasticPlugin#69]
Hello,

I facing up with problem, while doing some updates in UE4 using source control.
When i click _Source Control -> Sync/Update Workspace_  Unreal starts reloading some things and after some time, it crashed. Here is a engine error log: 

> Unhandled exception
> 
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_Engine
> UE4Editor_UnrealEd
> UE4Editor_UnrealEd
> UE4Editor_CoreUObject
> UE4Editor_UnrealEd
> UE4Editor_UnrealEd
> UE4Editor_PlasticSourceControl!FPlasticSourceControlMenu::ReloadPackages() [D:\Users\Levi\wkspaces\Atlantis_2\Plugins\UE4PlasticPlugin-master\Source\PlasticSourceControl\Private\PlasticSourceControlMenu.cpp:162]
> UE4Editor_PlasticSourceControl!FPlasticSourceControlMenu::OnSourceControlOperationComplete() [D:\Users\Levi\wkspaces\Atlantis_2\Plugins\UE4PlasticPlugin-master\Source\PlasticSourceControl\Private\PlasticSourceControlMenu.cpp:381]
> UE4Editor_PlasticSourceControl!TBaseRawMethodDelegateInstance<0,FPlasticSourceControlMenu,void __cdecl(TSharedRef<ISourceControlOperation,1> const &,enum ECommandResult::Type)>::ExecuteIfSafe() [D:\Program Files\Epic Games\UE_4.23\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:541]
> UE4Editor_PlasticSourceControl!FPlasticSourceControlProvider::Tick() [D:\Users\Levi\wkspaces\Atlantis_2\Plugins\UE4PlasticPlugin-master\Source\PlasticSourceControl\Private\PlasticSourceControlProvider.cpp:361]
> UE4Editor_SourceControl
> UE4Editor_UnrealEd
> UE4Editor_UnrealEd
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> UE4Editor
> kernel32
> ntdll

Could you help me to handle this problem ?

**Comment by SRombauts** [comment]
Hello,

I'll have to find the thread, but basically this is an Engine bug that you have with all Source Control plugins. It has to do with trying to relead folders with Redirectors IIRC.

Perhaps can you check this information by Syncing some sub-folders without redirectors, or by running "Cleanup redirectors" and submitting the result before?

Let me know!

**Comment by SRombauts** [comment]
Hi,

This is indeed à known issue of Unreal Engine itself, also affecting other source control Plugins. 

Here is the public issue that Epic opened to track the problem https://issues.unrealengine.com/issue/UE-63030
It has been marked as fixed in 4.24 though I haven't tried it myself yet. 

Cheers !

**Comment by SRombauts** [comment]
This is still happening in UE5, so I'll see how to rework it completely to only reload assets that need to

**Comment by SRombauts** [comment]
A fix has been released on December as https://github.com/PlasticSCM/UEPlasticPlugin/releases/tag/1.7.0 🎉
