### ISSUE TITLE
Request: Distribute the Plastic Plugin in UE4 marketplace, so it's easier to install

### ISSUE THREAD

**Issue by Ecnassianer** [SRombauts/UEPlasticPlugin#71]
All my other plugins for Unreal are install the UE4 marketplace, so it's easy to install them in a few clicks whenever I get a new engine version or start a new project. It would be real nice if the plastic integration was available there as well.

**Comment by SRombauts** [comment]
Hello, what version of Unreal Engine are you using?

This Plastic SCM plugin has been integrated by Epic Games into UE4.24! 
This should be even better, don't you think?

Cheers!

**Comment by Ecnassianer** [comment]
Ah, that's great! I'm on 4.23, so I haven't seen it yet. I'll look forward to not having to ever install it myself again! :D

**Comment by SRombauts** [comment]
I am reopening this, as we might want to offer a marketplace plugin for people that want an easy way to stay up to date

**Comment by SRombauts** [comment]
duplicated by https://github.com/SRombauts/UEPlasticPlugin/issues/113

**Comment by SRombauts** [comment]
The plugin is now [distributed in Unreal Engine Marketplace as a Code Plugin: https://www.unrealengine.com/marketplace/product/unity-version-control-plastic-scm
