### ISSUE TITLE
Automate Refresh

### ISSUE THREAD

**Issue by ka-132274** [SRombauts/UEPlasticPlugin#73]
Hi,

it would be great if the Refresh function could be automated to see if there are newer version of a file available without having to manually refresh.

We just had the problem that I checked out a blueprint, modified it and checked it in again. Afterwards, my colleague didn't refresh, the bp wasn't checked out any more, the bp wasn't shown as "new version available", and thus he was able to work further on the old version. So the problem showed up when he tried to check in his changes.

Is there already a way to prevent this?

**Comment by SRombauts** [comment]
Hello,

What version of the Engine and of the plugin are you using? 

A first answer is that there is already such à mechanism in Editor to automate update status of file. As such, there is also a cache and à notion of timeout. So it is just bad luck. 
Also, all this is in Editor and not configurable.

So there are two course of actions; I could modify the Engine Editor and hope for integration, or add à workaround in the plugin

**Comment by SRombauts** [comment]
`
namespace SourceControlConstants
{
	/** The maximum number of file/directory status requests we should dispatch in a tick */
	const int32 MaxStatusDispatchesPerTick = 64;

	/** The interval at which we refresh a file's state */
	const FTimespan StateRefreshInterval = FTimespan::FromMinutes(5.0);
}
`

**Comment by SRombauts** [comment]
There is no easy way to add proper Editor Settings to the source control module, that is, not with a UI... I'll try to figure this out

**Comment by SRombautsU** [comment]
The correct answer is that using exclusive checkout, a.k.a. Locks, is solving the issue entirely. Even better with [Smart Locks](https://blog.unity.com/engine-platform/unity-version-control-smart-locks)
