### ISSUE TITLE
UE4 Hangs/Crashes when updating source control, citing abnormal amounts of GPU usage

### ISSUE THREAD

**Issue by SteveChaTTG** [SRombauts/UEPlasticPlugin#86]
1. Connect UE4 to source control
2. Create a new blueprint file in the Content Browser
3. Delete the new blueprint files

Result:
UE4 will hang on updating source control and cause abnormal amounts of GPU usage. Might crash editor.

OR

UE4 will now crash if launch with source control enabled. Video of bug available upon request.

**Comment by ldmfield** [comment]
I am suffering with this issue atm any news on a fix?

**Comment by SRombauts** [comment]
This should now be worked around on master with https://github.com/SRombauts/UE4PlasticPlugin/commit/974ff8fbbefd7c95ef157f2ef04f70007888724e
see also https://github.com/SRombauts/UE4PlasticPlugin/issues/93 and https://github.com/SRombauts/UE4PlasticPlugin/issues/97

The workaround has been released as part of https://github.com/SRombauts/UE4PlasticPlugin/releases/tag/1.6.1 on the 2nd of August.

I am now working on a proper fix to be integrated into Unreal Engine 5.1

**Comment by SRombautsU** [comment]
I was first able to reproduce it by checking out 23k files from a huge test project on the cloud
Then more recently by deleting +1800 files using One File Per Actor
![image](https://user-images.githubusercontent.com/101874327/185191361-d01b20ea-1a87-451e-9cc8-3d0e721c5b35.png)

I'll be using this issue as a way to track the progress of the real fix to the Editor, versus the workaround submitted to the plugin

**Comment by SRombautsU** [comment]
I have started reproducing the issue in Unreal without any Source Control operation, with a simple infinite loop in the Provider, meaning it's purely a render thread issue (and I can see how other progress bars in the Editor code seem to handle this)
2022-08-17 (2)

**Comment by SRombauts** [comment]
I was first able to produce this a few months back when I triggered by mistake a checkout of 23k files in a huge One File Per Actor test project on the cloud
![2022-07-27](https://user-images.githubusercontent.com/868490/185192858-d7c5b576-9a5f-4abf-9034-65ce26189a7c.png)

I have now started reproducing the issue in Unreal without any Source Control operation, with a simple infinite loop in the Provider, meaning it's purely a render thread issue (and I can see how other progress bars in the Editor code seem to handle this)
It crashed my GPU after ~2min07s
<img width="892" alt="2022-08-17 (2)" src="https://user-images.githubusercontent.com/868490/185192960-1c95c9f9-ee64-49d2-951f-c9e9d30280c4.png">

**Comment by SRombauts** [comment]
A similar bug[ https://issues.unrealengine.com/issue/UE-93603](https://issues.unrealengine.com/issue/UE-93603) Directx 12 RHI can run out of video memory on long process (anims import)

has been fixed by adding End & BeginFrame on the RHI thread https://github.com/EpicGames/UnrealEngine/commit/4cbce19c2848723ccc01a4fba3133d663d64d4ae

**Comment by SRombauts** [comment]
And the official issue would be https://issues.unrealengine.com/issue/UE-100291 "Out of video memory" crash when attempting to save many assets with source control enabled.

A very recent one even mention the workaround I implemented in the plastic plugin! https://issues.unrealengine.com/issue/UE-160299 GPU memory leak during large source control operations:

> The crash has been seen in Git and SVN, and can be avoided by removing FScopedSourceControlProgress::Tick. This will prevent Slate from being ticked during the operation, but will prevent the throbber widget from animating.

**Comment by SRombauts** [comment]
PR to Epic Games :)
https://github.com/EpicGames/UnrealEngine/pull/9492 [UE-100291][UE-160299] Fix source control progress bar crashing out of video memory in case of long-running operation #9492

**Comment by SRombauts** [comment]
The proper fix has been submitted to ue5-main https://github.com/EpicGames/UnrealEngine/commit/67dacf2baaafe0d9b6fb5eeb5b179fb5b871a4bf 

It will be part of UE 5.1 release :)
