### ISSUE TITLE
UE4 4.26 Collections not working

### ISSUE THREAD

**Issue by kwljunky** [SRombauts/UEPlasticPlugin#87]
Hey guys,

Creating a shared collection is not working with the plugin, it is working with other SCM plugins. 

Steps to reproduce: 

1. Have plastic SCM plugin enabled in editor
2. Make a shared collection 
3. Add things to the shared collection. 
4. It will auto commit. 
5. Re-open editor, and when hovering over the shared collection we get a collection is missing it's source control provider, please check your source control plugins. 

Tried against perforce, tried again SVN and git plugins, no issues. 

Thanks.

**Comment by SRombauts** [comment]
Thanks for reporting the issue, it has now been fixed in master as of https://github.com/SRombauts/UEPlasticPlugin/issues/87
