### ISSUE TITLE
Sync/Update workspace takes ages on a big unreal project

### ISSUE THREAD

**Issue by PreyK** [SRombauts/UEPlasticPlugin#89]
SOLVED
https://github.com/SRombauts/UE4PlasticPlugin/issues/89#issuecomment-980323099

Hello!
Our company works on heavy industrial projects in unreal.
Our project sizes are between 30-150 Gb regularly.
When I click on Sync/Update workspace it reloads ALL the assets in the project (all 150 gb of it) even if it's not changed, not touched etc..
![image](https://user-images.githubusercontent.com/1968543/143576129-08b9fddd-3c43-4b55-8fb4-2022f097c6cf.png)
![image](https://user-images.githubusercontent.com/1968543/143576409-6952d9d8-2857-430a-b737-0f852174c3a8.png)
It looks like as per https://github.com/SRombauts/UE4PlasticPlugin/blob/da88875a28463b19f64d3731693fad4b49c40a0f/Source/PlasticSourceControl/Private/PlasticSourceControlMenu.cpp#L173 
and
https://github.com/SRombauts/UE4PlasticPlugin/blob/da88875a28463b19f64d3731693fad4b49c40a0f/Source/PlasticSourceControl/Private/PlasticSourceControlMenu.cpp#L187
It explicitly reloads all the packages even when it's not needed.
Is there a practical reason it's done this way?

Couldn't this be done as getting the stuff that changed from "cm" and reloading only that?

Is this project still maintained? I know Unity just bought plastic but we'd really need something for unreal as an anternative to Perforce.
We don't want to use Gluon or Plastic GUI for this because artists and staying in unreal all the time ideally.

I'll look into this for our internal use and try to come up with something for big projects.

If this plugin is still maintained and PR-s are welcome I'm happy to make one if I get somewhere.
In the meantime if anyone looked into this before any help or insight would be greatly appreciated :D

**Comment by PreyK** [comment]
Update:
It looks like this was a problem on our end.
The project contained special characters in filenames (áéű) and the plugin could not update files because it was an invalid path.
When it failed as per
https://github.com/SRombauts/UE4PlasticPlugin/blob/da88875a28463b19f64d3731693fad4b49c40a0f/Source/PlasticSourceControl/Private/PlasticSourceControlMenu.cpp#L187
It reloaded all of the packages.
Because reloading took a lot of time by the time the project reloaded the notification about failing to sync disappeared so it looked like "no error, just whole project reload"

Refactoring our filenames and paths solved it, it no longer reloads the whole project on sync/update and works without errors

**Comment by SRombauts** [comment]
Thanks for the report and the analysis, it may help others!

**Comment by SRombauts** [comment]
There is still a couple of underlying issue here, so I am reopening it for tracking purpose

**Comment by SRombautsU** [comment]
The underlying issue with accents in filenames have now been fixed #18

**Comment by SRombautsU** [comment]
Actually, the fact that it reloads everything and take ages is still a ongoing issue!

**Comment by SRombauts** [comment]
Hello, this has been fixed recently, with  https://github.com/PlasticSCM/UEPlasticPlugin/pull/46 and  https://github.com/PlasticSCM/UEPlasticPlugin/pull/47  

Cheers!
